### ISSUE TITLE
Phkondo v1.5 - Support Request

### ISSUE THREAD

**Issue by arnaud-42** [pHAlkaline/phkondo#19]
Hello,
I finded a bug im the "Support Request" module.
I use the v1.5 (from your website)

If you create a new request and then edit this request the property is change by another one (from another condo)

I have 2 condo.
the first have property 1,2 and 3
the second have A B and C

I opened the support with property B ... if i edit the request i can't change the preoperty but it's set to 3 ...

**Comment by pHAlkaline** [comment]
Check if is this behavior ?
This normally happens when user as several tabs / windows open and changes selected condo on one tab this changes condo on session ... meaning that every other windows / tabs opened will also be with new selected condo.
We already worked on this but it will be only on next versions.

**Comment by arnaud-42** [comment]
I only have 1 tab/windows/

**Comment by arnaud-42** [comment]
Thanks :)
